export const CHANGE_CHAT = "CHANGE_CHAT";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const GET_RANDOM_ANSWER_SUCCESS = "GET_RANDOM_ANSWER_SUCCESS";
